create_acc_title = '.page-title'
name_field = '[id="firstname"]'
last_name_field = '[id="lastname"]'
email_field = '[id="email_address"]'
password_field = '[id="password"]'
password_confirm_field = '[id="password-confirmation"]'
create_acc_button = 'button[title="Create an Account"]'
name_error = '[id="firstname-error"]'
last_name_error = '[id="lastname-error"]'
email_error = '[id="email_address-error"]'
password_error = '[id="password-error"]'
conf_pass_error = '[id="password-confirmation-error"]'