eco_friendly_title = '[class="page-title"]'
sort_button = '//select[@id="sorter"]'
price_sort = '//select[@id="sorter"][1]/child::option[@value="price"]'
name_sort = '//select[@id="sorter"][1]/child::option[@value="name"]'
position_sort = '//select[@id="sorter"][1]/child::option[@value="position"]'
product_list = 'ol[class*="products list"]'
first_item = '//li[@class="item product product-item"][1]'
one_item = '//li[@class="item product product-item"]'
first_item_cart_button = '//li[@class="item product product-item"][1]/descendant::button'
sort_switcher_button = '//*[@data-role="direction-switcher"][1]'