eco_friendly_title = '[class="page-title"]'
sort_button = '//select[@id="sorter"]'
product_list = 'ol[class*="products list"]'
first_item = '//li[@class="item product product-item"][1]'
one_item = '//li[@class="item product product-item"]'
first_item_cart_button = '//li[@class="item product product-item"][1]/descendant::button'